// @flow

// GENERAL
export const INIT_APP = 'INIT_APP';
export const REQUEST_SAVE_ACCOUNT = 'REQUEST_SAVE_ACCOUNT';
export const REQUEST_SAVE_TIMELINE = 'REQUEST_SAVE_TIMELINE';
export const LOAD_ACCOUNT_DATA_SUCCESSED = 'LOAD_ACCOUNT_DATA_SUCCESSED'
export const LOAD_TIMELINE_DATA_SUCCESSED = 'LOAD_TIMELINE_DATA_SUCCESSED';
export const LOAD_DATA_FAILED = 'LOAD_DATA_FAILED';

// Account
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UPDATE_USERDATA = 'UPDATE_USERDATA';

// AUTHORIZATION
export const OPEN_PIN_AUTHORIZATION_WINDOW = 'OPEN_PIN_AUTHORIZATION_WINDOW';
export const REQUEST_AUTHORIZATION = 'REQUEST_AUTHORIZATION';
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';

// CONTENT
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const CONTENT_SET_REPLY = 'CONTENT_SET_REPLY';

// Timeline
export const ADD_TIMELINE = 'ADD_TIMELINE';
export const DELETE_TIMELINE = 'DELETE_TIMELINE';
export const OWNERINDEX_REASSIGN = 'OWNERINDEX_REASSIGN';

export const UPDATE_CONTENT_TEXT = 'UPDATE_CONTENT_TEXT';
export const CLEAR_FORM = 'CLEAR_FORM';
export const SET_TIMELINE_MENU = 'SET_TIMELINE_MENU';
export const SET_IN_PROGRESS_STATUS = 'SET_IN_PROGRESS_STATUS';

// API
export const REQUEST_CALL_API = 'REQUEST_CALL_API';
export const CALL_API_FAILED = 'CALL_API_FAILED';

// Dialog
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const CREATE_TL_DIALOG_SELECT_ACCOUNT = 'CREATE_TL_DIALOG_SELECT_ACCOUNT';
export const CREATE_TL_DIALOG_SELECT_TIMELINE_TYPE = 'CREATE_TL_DIALOG_SELECT_TIMELINE_TYPE';

export const CREATE_AC_SELECT_INSTANCE = 'CREATE_AC_SELECT_INSTANCE';
export const CREATE_AC_FORWARD_INPUT_DATA = 'CREATE_AC_FORWARD_INPUT_DATA';
export const CREATE_AC_FORWARD_PIN_AUTH = 'CREATE_AC_FORWARD_PIN_AUTH';
export const CREATE_AC_RECEIVE_PIN_ERR = 'CREATE_AC_RECEIVE_PIN_ERR';
export const CREATE_AC_BACK_SECTION = 'CREATE_AC_BACK_SECTION';

// DEV OPTION
export const SET_DEV_DATA = 'SET_DEV_DATA';
